FROM jjanzic/docker-python3-opencv:opencv-3.4.1
RUN pip install pip -U && \
#    python -m pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
    python -m pip config set global.index-url https://mirrors.aliyun.com/pypi/simple
RUN pip install PyYaml